# Generated by Django 3.1.2 on 2021-12-23 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_auto_20211214_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='slug',
        ),
    ]
